services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - APP_URL=http://localhost:8080
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SUPERADMIN_EMAIL=supadmin@ventry.com
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
    volumes:
      - ./logs:/app/logs
    networks:
      - ventry-network
    depends_on:
      - seed-superadmin
    command: ["node", "dist/server.js"]

  seed-superadmin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - APP_URL=http://localhost:3001
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SUPERADMIN_EMAIL=supadmin@ventry.com
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
    command: ["node", "dist/scripts/seed-superadmin.js"]
    networks:
      - ventry-network

networks:
  ventry-network:
    driver: bridge